title: Additive Motherhood
description: Quantitative Genetics | New Mom | Modeling Life's Variance
theme: jekyll-theme-cayman

header_pages:
  - genetics/README.md
  - motherhood/README.md
  - travel/README.md
